### ISSUE TITLE
mirrage的b2楼挂窗烟需要优化

### ISSUE THREAD

**Issue by Diorite9248** [eLecCap1taL/CSRM#1]
这颗烟扔出去之后靠近窗户下沿的地方会漏缝，之前1.2版本自己瞄点扔的时候似乎有一个角度可以覆盖得更好，也许可以微调一下视角转动的角度

**Comment by eLecCap1taL** [comment]
能分享一下setang吗 :)

**Comment by Diorite9248** [comment]
> 能分享一下setang吗 :)

抱歉，我不懂怎么写cfg，只是实战中用起来发现的

**Comment by eLecCap1taL** [comment]
> > 能分享一下setang吗 :)
> 
> 抱歉，我不懂怎么写cfg，只是实战中用起来发现的

如果您能找到一个稳定的描点的话，只需要站在位置上，瞄好，控制台输入getpos，就能得到一串代码，它储存了你的描点信息，我指的就是它。如果可以分享的话，非常感谢！如果没有稳定描点也没关系，我已经在尝试优化了
