### ISSUE TITLE
如果作者大大有添加更多道具打算的话可以考虑一下这几个

### ISSUE THREAD

**Issue by Diorite9248** [eLecCap1taL/CSRM#2]
这几个道具都是在出生点（或安全位置）投掷，站位固定便于寻找，投掷方式简单，并且有一定的战术意义
1.核子危机 外场一线烟/正门瀑布烟 BV1Wx421y7Nq BV12N41157Vu
2.远古遗迹 CT快匪口烟 BV1jgYzeLE7b   T快vip烟 BV1dw411G73s
                  A厅外丢警家烟/甜甜圈烟/神庙烟 B门外丢一道烟/二道烟/小黑屋烟/死点火 BV1M64y1V7U8 p14-p16 p22-25
3.荒漠迷城 常规vip烟（站垃圾桶那里的），针对无法在出生位投掷vip快烟的情况 BV15C4y197ZH p2

在此抛砖引玉，希望作者的cfg越来越完善！

**Comment by eLecCap1taL** [comment]
所有不是一瞬间投掷的道具，CFG都做不了。包括什么走一步跳投，静步走一步跳投，按D一会后跳投都不行
其余的我会加的
谢谢反馈
