### ISSUE TITLE
V2.2版本出现 [Console] Unknown command 

### ISSUE THREAD

**Issue by Tncent** [eLecCap1taL/CSRM#3]
Version: V2.2

在 Preference.cfg 中存在 Bind key +DisableIMStop 的配置，但将其配置到 大小写锁定 (Capslock) 时无效
控制台中提示

[Console] Unknown command '+DisableIMStop'!
[Console] Unknown command '-DisableIMStop'!

**Comment by eLecCap1taL** [comment]
> Version: V2.2
> 
> 在 Preference.cfg 中存在 Bind key +DisableIMStop 的配置，但将其配置到 大小写锁定 (Capslock) 时无效 控制台中提示
> 
> [Console] Unknown command '+DisableIMStop'! [Console] Unknown command '-DisableIMStop'!
是按下按键的时候出现 Unknown command 吗？
理论上无论如何不应该出现 Unknown command，因为其在 IMStopMain.cfg 中明确做了定义，Main.cfg 会加载这个文件
能否提供完整的控制台录屏，或者打包发一下你现在的csrm文件夹？
